package com.dipanshushukla.realtimechatappmessageservice.repository;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Optional;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;

import com.dipanshushukla.realtimechatappmessageservice.entity.ChatRoom;
import com.dipanshushukla.realtimechatappmessageservice.factory.MessageDataFactory;

@DataJpaTest
class ChatRoomRepositoryTest {

    @Autowired
    private ChatRoomRepository chatRoomRepository;

    @Test
    @DisplayName("Should successfully save and retrieve a ChatRoom")
    void saveAndFindChatRoom() {
        // Arrange
        ChatRoom chatRoom = MessageDataFactory.createValidChatRoom();
        chatRoom.setChatId(null); // Ensure ID is auto-generated by the DB if applicable

        // Act
        ChatRoom savedRoom = chatRoomRepository.save(chatRoom);

        // Assert
        assertNotNull(savedRoom);
        assertNotNull(savedRoom.getChatId());

        Optional<ChatRoom> retrievedRoomOpt = chatRoomRepository.findById(savedRoom.getChatId());
        assertTrue(retrievedRoomOpt.isPresent());
        assertEquals("Test Chat", retrievedRoomOpt.get().getName());
    }

}
